# 2장. 다항 선형 회귀

---

## 학습 목표
- 다항 선형 회귀 모델의 구조와 고차항이 추가될수록 변화하는 특성을 학습합니다. 
- 다항 선형 회귀 class를 구현합니다.

---

## 목차

### 1. 다항 선형 회귀 모델
1. 다항 선형 회귀란?

### 2. 이차항 선형 회귀
1. 이차항 선형 회귀 모델
2. 이차항 선형 회귀 class 구조
3. scikit-learn 모듈

### 3. 고차항 선형 회귀
1. 고차항 선형 회귀 모델
2. 고차항 선형 회귀 class 구조
3. scikit-learn 모듈


---

## 2.  이차항 선형 회귀

### 2-1. 이차항 선형 회귀 모델

#### 학습 데이터

이차항 선형 회귀 모델을 정의하기 전에 데이터부터 정의해 봅시다.

##### 학습용 feature 데이터

> $$\mathbf{x_{feature}}=\begin{pmatrix}
 x_{1} \\ 
 x_{2} \\ 
 \vdots  \\ 
 x_{N} 
\end{pmatrix}, \;\;\;\;\; $$

##### 학습용 lable 데이터

> $$\mathbf{y}=\begin{pmatrix}
y_1 \\ 
y_2 \\ 
\vdots \\ 
y_N
\end{pmatrix}. \;\;\;\;\; $$

처음부터 $p$개의 일반화 된 feature 데이터를 정의를 사용하여 식을 전개하기엔 쉽지 않기에, 우선 한 종류의 feature column을 갖는 feature 데이터로 시작해서 고차항 파트에서 일반화 해봅시다.

#### 이차항 선형 회귀 모델

이제 이차항 선형 회귀 모델에 대해서 정의해 봅시다.

이차항 선형 회귀 모델은 1개의 feature column을 입력으로 하여 이차 함수 형태로 회귀 모델을 구현한 것을 의미합니다.

##### 이차항 선형 회귀 모델

> $$f(x_i)=w_0+w_1 x_{i}+w_2 x_{i}^{2}$$

$w_0, w_1, w_2$은 1차 함수 모델 $f()$의 파라미터를 의미합니다.

다중 선형 회귀에서처럼 least square solution을 구하기 위해서 보다 효율적으로 행렬식으로 변환해 보겠습니다.

##### 이차항 선형 회귀 모델

> $$F(X) = X\mathbf{w}$$

> $$X=\begin{pmatrix}
1 & x_{1} & x_{1}^{2} \\ 
1 & x_{2} & x_{2}^{2} \\ 
\vdots & \vdots  & \vdots \\ 
1 & x_{N} & x_{N}^{2}
\end{pmatrix}, \;\;\;\;\; \mathbf{w}=\begin{pmatrix}
w_0 \\ 
w_1 \\ 
w_2 \\ 
\end{pmatrix}, \;\;\;\;\; $$

$X$는 기존 feature 데이터에서 1만으로 이루어진 column과 $x_{i}^{2}$ 데이터의 column을 추가한 형태를 의미합니다.

##### <예제 1> 이차항 선형 회귀 모델

이차항 선형 회귀 모델을 만들어 feature 데이터를 입력하고 예측값을 출력하여 봅시다.

In [8]:
import numpy as np

# feature 데이터
X_feature = np.array([1, 2, 3, 4]).reshape((-1,1))
# 1 column 이 추가된 feature 데이터
X = np.c_[np.ones((X_feature.shape[0],1)),X_feature]
# 제곱 데이터 column이 추가된 feature 데이터
X = np.c_[X,X_feature**2]
# label 데이터
Y = np.array([3.1, 4.9, 7.2, 8.9]).reshape((-1,1))

print("X_feature: \n{}\n".format(X_feature))
print("X: \n{}\n".format(X))
print("Y: \n{}\n".format(Y))

X_feature: 
[[1]
 [2]
 [3]
 [4]]

X: 
[[ 1.  1.  1.]
 [ 1.  2.  4.]
 [ 1.  3.  9.]
 [ 1.  4. 16.]]

Y: 
[[3.1]
 [4.9]
 [7.2]
 [8.9]]



In [9]:
# 파라미터 column 설정
w = np.array([1,1,1]).reshape((-1,1))

# 다항 선형 모델 함수
def F_X(w,X):
    return np.dot(X,w)

print("F(X): \n{}\n".format(F_X(w,X)))

F(X): 
[[ 3.]
 [ 7.]
 [13.]
 [21.]]



#### loss 함수 최적화

다항 선형 회귀 모델을 정리 했으니 마지막으로 loss 함수를 정리해 봅시다.

##### loss 함수

> $$
\begin{aligned}
Loss(\mathbf{w})&=\frac{1}{N}\sum_{i=1}^{N}(y_i-f(\mathbf{x_i}))^{2} \\
&=\frac{1}{N}(\mathbf{y}-X\mathbf{w})^{T}(\mathbf{y}-X\mathbf{w})
\end{aligned}$$

위 수식에서 알 수 있듯이, 다중 선형 회귀와 형태는 같습니다. 그저 2 번째 feature 데이터의 column이 첫 번째 column의 제곱이란 것만 다를뿐입니다. 

따라서 같은 방식으로 least square solution을 구할 수 있습니다.

##### 이차항 선형 회귀 파라미터 least square solution

> $$\mathbf{\widehat{w}}=(X^{T}X)^{-1}X^{T}\mathbf{y}$$

$\mathbf{\widehat{w}}$은 loss 값을 최소로 만드는 파라미터 벡터를 의미합니다.

##### <예제 2> 이차항 선형 회귀 구현 - least square

이차항 선형 회귀 최적의 파라미터를 least square로 구하고 최소화 된 loss 값을 출력해 봅시다.

In [10]:
import numpy as np


# feature 데이터
X_feature = np.array([1, 2, 3, 4]).reshape((-1,1))
# 1 column 이 추가된 feature 데이터
X = np.c_[np.ones((X_feature.shape[0],1)),X_feature]
# 제곱 데이터 column이 추가된 feature 데이터
X = np.c_[X,X_feature**2]
# label 데이터
Y = np.array([3.1, 4.9, 7.2, 8.9]).reshape((-1,1))


w = np.dot(np.linalg.inv(np.dot(X.transpose(),X)),np.dot(X.transpose(),Y))

# 다중 선형 모델 함수
def F_X(w,X):
    return np.dot(X,w)


def loss(f_x, label_data):
    error = label_data - f_x
    ls = np.mean(error**2)
    return ls

print("loss: {}\n".format(loss(F_X(w,X),Y)))

loss: 0.015124999999999977



### 2-2. 이차항 선형 회귀 class 구조

위에서 수행된 것을 확인해보면 이차항 선형 회귀의 class는 $X$를 만들어주는 것 이외에는 다중 선형 회귀의 class와 다를게 없습니다.

##### <예제 3> 이차항 선형 회귀 class

class는 least square를 사용했던 단순 선형 회귀 구조와 비슷하게 초기화, 학습, 예측, loss 함수로 구성합니다.

In [12]:
import numpy as np

class sec_linaer_regression:
    # 초기화 함수
    def __init__(self, initial_w):
        self.w = initial_w
        
    # 학습 함수    
    def fit(self, feature, label):
        
        # 이차항을 추가하여 X를 만드는 과정
        X = np.c_[np.ones((feature.shape[0],1)),feature]
        X = np.c_[X,feature**2]
        self.w = np.dot(np.linalg.inv(np.dot(X.transpose(),X)),np.dot(X.transpose(),label))

        
    # 예측값 계산 함수
    def predict(self, feature):
        
        # 이차항을 추가하여 X를 만드는 과정
        X = np.c_[np.ones((feature.shape[0],1)),feature]
        X = np.c_[X,feature**2]
        prediction = np.dot(X,self.w)
        
        return prediction
    
    # loss 값 계산 함수
    def loss(self, feature, label):
        
        error = label - self.predict(feature)
        ls = np.mean(error**2)
        
        return ls

##### <예제 4> 이차항 선형 회귀 학습

`<예제 3>` 이차항 선형 회귀 class에서 구현한 class를 사용하여 학습 과정을 수행해 봅시다.

In [13]:
import numpy as np

# 학습용 데이터
feature_data = np.array([1, 2, 3, 4]).reshape((-1,1))
label_data = np.array([3.1,4.9,7.2,8.9]).reshape((-1,1))

# 파라미터 0으로 초기화
w = np.zeros((feature_data.shape[1]+1,1))
            
# 다중 선형 회귀 모델 불러오기 및 초기화
model = sec_linaer_regression(w)

# 학습 수행
model.fit(feature_data, label_data)

print("loss: {}\n".format(model.loss(feature_data, label_data))) 

loss: 0.015124999999999977



### 2-3. scikit-learn 모듈

scikit-learn에서는 이차항 선형 회귀 또한 class가 따로 존재 하지 않습니다. 

역시나 단순 선형 회귀에서 사용한 `LinearRegression()` class는 이차항 선형 회귀에서도 그대로 사용됩니다.

다만 입력하는 feature를 $X$로 만드는 과정이 없기에 `PolynomialFeatures` 을 사용하여 $X$를 생성합니다.

##### <예제 5> `PolynomialFeatures` 사용하기

이차항 선형 회귀를 scikit-learn으로 수행하기 위해서 `PolynomialFeatures`을 사용하여 feature 데이터의 이차항 column 배열을 추가해 봅시다.

In [15]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

feature_data = np.array([1, 2, 3, 4]).reshape((-1,1))
print("feature data: \n{}\n".format(feature_data))

# 2차항 선형 회귀에 해당되는 2를 초기값으로 입력
poly = PolynomialFeatures(2)

# fit 함수를 사용하여 X로 변환 작업을 수행
X = poly.fit_transform(feature_data)
print("X: \n{}\n".format(X))


feature data: 
[[1]
 [2]
 [3]
 [4]]

X: 
[[ 1.  1.  1.]
 [ 1.  2.  4.]
 [ 1.  3.  9.]
 [ 1.  4. 16.]]



`PolynomialFeatures`을 사용하여 $X$가 준비되었다면 단순 선형 회귀와 같은 방법으로 학습을 수행할 수 있습니다.

##### <예제 6>  scikit-learn을 사용한 이차항 선형 회귀

`<예제 4>` 에서와 같은 데이터를 사용하여 이번엔 scikit-learn의 loss 값을 출력해 봅시다.

In [16]:
import numpy as np
from sklearn.linear_model import LinearRegression

# 모델 설정
sci_model = LinearRegression()

# 학습 수행
sci_model.fit(X, label_data)

# scikit-learn 에서는 loss 함수가 모델안에 내정되어 있지 않기에 정의
def loss(prediction, label):
        
    error = label - prediction
    ls = np.mean(error**2)

    return ls

print("loss: {}\n".format(loss(sci_model.predict(X), label_data))) 

loss: 0.015125000000000001



---